export { default as HomePage } from './HomePage';
export { default as LandingPage } from './LandingPage';
// export { default as LoginPage } from './LoginPage';
// export { default as NewArticlePage } from './NewArticlePage';
// export { default as NotFoundPage } from './NotFoundPage';
// export { default as NotificationPage } from './NotificationPage';
// export { default as ArticlesPage } from './ArticlesPage';
// export { default as ArticleDetailPage } from './ArticleDetailPage';
// export { default as ProfilePage } from './ProfilePage';
// export { default as SearchPage } from './SearchPage';
export { default as SignUpPage } from './SignUpPage';
// export { default as ProfileEditPage } from './ProfileEditPage';
// export { default as ChangePasswordPage } from './ChangePasswordPage';
// export { default as LoadingPage } from './LoadingPage';
// export { default as ProtectedRouter } from './ProtectedRouter';
// export { default as ArticleEditPage } from './ArticleEditPage';
